<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Question;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            // SÉRIE 6
            [
                'serie' => '6',
                'enunciado' => 'Qual é a unidade básica da matéria?',
                'alternativa_a' => 'Átomo',
                'alternativa_b' => 'Célula',
                'alternativa_c' => 'Molécula',
                'alternativa_d' => 'Elétron',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '6',
                'enunciado' => 'Qual é o maior planeta do Sistema Solar?',
                'alternativa_a' => 'Terra',
                'alternativa_b' => 'Júpiter',
                'alternativa_c' => 'Saturno',
                'alternativa_d' => 'Marte',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '6',
                'enunciado' => 'Qual destes é um estado físico da água?',
                'alternativa_a' => 'Gelo',
                'alternativa_b' => 'Vapor',
                'alternativa_c' => 'Líquido',
                'alternativa_d' => 'Todos os anteriores',
                'resposta_correta' => 'D',
            ],
            [
                'serie' => '6',
                'enunciado' => 'O que é necessário para ocorrer a fotossíntese?',
                'alternativa_a' => 'Luz',
                'alternativa_b' => 'Água',
                'alternativa_c' => 'Gás carbônico',
                'alternativa_d' => 'Todas as anteriores',
                'resposta_correta' => 'D',
            ],
            [
                'serie' => '6',
                'enunciado' => 'Qual destes animais é um mamífero?',
                'alternativa_a' => 'Cobra',
                'alternativa_b' => 'Sapo',
                'alternativa_c' => 'Cachorro',
                'alternativa_d' => 'Galinha',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '6',
                'enunciado' => 'Qual é o principal gás da atmosfera?',
                'alternativa_a' => 'Oxigênio',
                'alternativa_b' => 'Nitrogênio',
                'alternativa_c' => 'Gás carbônico',
                'alternativa_d' => 'Hidrogênio',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '6',
                'enunciado' => 'Qual destes é um órgão do corpo humano?',
                'alternativa_a' => 'Coração',
                'alternativa_b' => 'Ossos',
                'alternativa_c' => 'Pele',
                'alternativa_d' => 'Músculo',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '6',
                'enunciado' => 'O que é energia renovável?',
                'alternativa_a' => 'Energia que não se esgota',
                'alternativa_b' => 'Energia do petróleo',
                'alternativa_c' => 'Energia nuclear',
                'alternativa_d' => 'Energia do carvão',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '6',
                'enunciado' => 'Qual é o menor planeta do Sistema Solar?',
                'alternativa_a' => 'Mercúrio',
                'alternativa_b' => 'Vênus',
                'alternativa_c' => 'Terra',
                'alternativa_d' => 'Marte',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '6',
                'enunciado' => 'Qual destes é um exemplo de sólido?',
                'alternativa_a' => 'Água',
                'alternativa_b' => 'Gelo',
                'alternativa_c' => 'Vapor',
                'alternativa_d' => 'Ar',
                'resposta_correta' => 'B',
            ],
            // SÉRIE 7
            [
                'serie' => '7',
                'enunciado' => 'Qual é o planeta mais próximo do Sol?',
                'alternativa_a' => 'Terra',
                'alternativa_b' => 'Vênus',
                'alternativa_c' => 'Marte',
                'alternativa_d' => 'Mercúrio',
                'resposta_correta' => 'D',
            ],
            [
                'serie' => '7',
                'enunciado' => 'Qual é o maior órgão do corpo humano?',
                'alternativa_a' => 'Coração',
                'alternativa_b' => 'Fígado',
                'alternativa_c' => 'Pele',
                'alternativa_d' => 'Pulmão',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '7',
                'enunciado' => 'Qual é a função dos glóbulos vermelhos?',
                'alternativa_a' => 'Defesa do corpo',
                'alternativa_b' => 'Transporte de oxigênio',
                'alternativa_c' => 'Digestão',
                'alternativa_d' => 'Produção de hormônios',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '7',
                'enunciado' => 'Qual é o símbolo químico do ferro?',
                'alternativa_a' => 'Fe',
                'alternativa_b' => 'F',
                'alternativa_c' => 'Ir',
                'alternativa_d' => 'Fr',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '7',
                'enunciado' => 'Qual é o maior animal terrestre?',
                'alternativa_a' => 'Elefante',
                'alternativa_b' => 'Girafa',
                'alternativa_c' => 'Rinoceronte',
                'alternativa_d' => 'Hipopótamo',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '7',
                'enunciado' => 'Qual é a capital do Brasil?',
                'alternativa_a' => 'Rio de Janeiro',
                'alternativa_b' => 'Brasília',
                'alternativa_c' => 'São Paulo',
                'alternativa_d' => 'Salvador',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '7',
                'enunciado' => 'Qual é o maior oceano do mundo?',
                'alternativa_a' => 'Atlântico',
                'alternativa_b' => 'Índico',
                'alternativa_c' => 'Pacífico',
                'alternativa_d' => 'Ártico',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '7',
                'enunciado' => 'Qual é o nome do processo de transformação da lagarta em borboleta?',
                'alternativa_a' => 'Metamorfose',
                'alternativa_b' => 'Fotossíntese',
                'alternativa_c' => 'Respiração',
                'alternativa_d' => 'Digestão',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '7',
                'enunciado' => 'Qual é o nome do satélite natural da Terra?',
                'alternativa_a' => 'Lua',
                'alternativa_b' => 'Sol',
                'alternativa_c' => 'Marte',
                'alternativa_d' => 'Vênus',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '7',
                'enunciado' => 'Qual é o nome do maior rio do mundo?',
                'alternativa_a' => 'Nilo',
                'alternativa_b' => 'Amazonas',
                'alternativa_c' => 'Yangtzé',
                'alternativa_d' => 'Mississipi',
                'resposta_correta' => 'B',
            ],
            // SÉRIE 8
            [
                'serie' => '8',
                'enunciado' => 'Qual é a fórmula da água?',
                'alternativa_a' => 'CO2',
                'alternativa_b' => 'H2O',
                'alternativa_c' => 'O2',
                'alternativa_d' => 'NaCl',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '8',
                'enunciado' => 'Qual é o nome do processo de passagem do estado sólido para o líquido?',
                'alternativa_a' => 'Fusão',
                'alternativa_b' => 'Sublimação',
                'alternativa_c' => 'Condensação',
                'alternativa_d' => 'Evaporação',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '8',
                'enunciado' => 'Qual é o nome do maior planeta do Sistema Solar?',
                'alternativa_a' => 'Saturno',
                'alternativa_b' => 'Júpiter',
                'alternativa_c' => 'Terra',
                'alternativa_d' => 'Netuno',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '8',
                'enunciado' => 'Qual é o nome do processo de transformação do vapor em líquido?',
                'alternativa_a' => 'Condensação',
                'alternativa_b' => 'Fusão',
                'alternativa_c' => 'Sublimação',
                'alternativa_d' => 'Solidificação',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '8',
                'enunciado' => 'Qual é o nome do maior osso do corpo humano?',
                'alternativa_a' => 'Fêmur',
                'alternativa_b' => 'Tíbia',
                'alternativa_c' => 'Úmero',
                'alternativa_d' => 'Rádio',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '8',
                'enunciado' => 'Qual é o nome do processo de respiração das plantas?',
                'alternativa_a' => 'Fotossíntese',
                'alternativa_b' => 'Respiração celular',
                'alternativa_c' => 'Transpiração',
                'alternativa_d' => 'Fermentação',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '8',
                'enunciado' => 'Qual é o nome do maior animal do mundo?',
                'alternativa_a' => 'Elefante',
                'alternativa_b' => 'Baleia-azul',
                'alternativa_c' => 'Tubarão-branco',
                'alternativa_d' => 'Girafa',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '8',
                'enunciado' => 'Qual é o nome do processo de transformação do líquido em vapor?',
                'alternativa_a' => 'Evaporação',
                'alternativa_b' => 'Fusão',
                'alternativa_c' => 'Condensação',
                'alternativa_d' => 'Sublimação',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '8',
                'enunciado' => 'Qual é o nome do maior deserto do mundo?',
                'alternativa_a' => 'Saara',
                'alternativa_b' => 'Atacama',
                'alternativa_c' => 'Gobi',
                'alternativa_d' => 'Kalahari',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '8',
                'enunciado' => 'Qual é o nome do maior rio da Ásia?',
                'alternativa_a' => 'Yangtzé',
                'alternativa_b' => 'Ganges',
                'alternativa_c' => 'Mekong',
                'alternativa_d' => 'Lena',
                'resposta_correta' => 'A',
            ],
            // SÉRIE 9
            [
                'serie' => '9',
                'enunciado' => 'Qual é a principal fonte de energia da Terra?',
                'alternativa_a' => 'Vento',
                'alternativa_b' => 'Sol',
                'alternativa_c' => 'Água',
                'alternativa_d' => 'Carvão',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '9',
                'enunciado' => 'Qual é o nome do maior continente do mundo?',
                'alternativa_a' => 'África',
                'alternativa_b' => 'Europa',
                'alternativa_c' => 'Ásia',
                'alternativa_d' => 'América',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '9',
                'enunciado' => 'Qual é o nome do maior lago do mundo?',
                'alternativa_a' => 'Lago Superior',
                'alternativa_b' => 'Lago Vitória',
                'alternativa_c' => 'Mar Cáspio',
                'alternativa_d' => 'Lago Baikal',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '9',
                'enunciado' => 'Qual é o nome do maior arquipélago do mundo?',
                'alternativa_a' => 'Indonésia',
                'alternativa_b' => 'Filipinas',
                'alternativa_c' => 'Japão',
                'alternativa_d' => 'Maldivas',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '9',
                'enunciado' => 'Qual é o nome do maior golfo do mundo?',
                'alternativa_a' => 'Golfo do México',
                'alternativa_b' => 'Golfo Pérsico',
                'alternativa_c' => 'Golfo de Bengala',
                'alternativa_d' => 'Golfo de Aden',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '9',
                'enunciado' => 'Qual é o nome do maior mar do mundo?',
                'alternativa_a' => 'Mar Mediterrâneo',
                'alternativa_b' => 'Mar do Norte',
                'alternativa_c' => 'Mar de Bering',
                'alternativa_d' => 'Mar de Coral',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '9',
                'enunciado' => 'Qual é o nome do maior vulcão do mundo?',
                'alternativa_a' => 'Etna',
                'alternativa_b' => 'Krakatoa',
                'alternativa_c' => 'Mauna Loa',
                'alternativa_d' => 'Vesúvio',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '9',
                'enunciado' => 'Qual é o nome do maior arquipélago do Brasil?',
                'alternativa_a' => 'Fernando de Noronha',
                'alternativa_b' => 'Ilha de Marajó',
                'alternativa_c' => 'Ilhabela',
                'alternativa_d' => 'Abrolhos',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '9',
                'enunciado' => 'Qual é o nome do maior deserto do Brasil?',
                'alternativa_a' => 'Deserto do Atacama',
                'alternativa_b' => 'Deserto do Saara',
                'alternativa_c' => 'Deserto do Jalapão',
                'alternativa_d' => 'Deserto do Kalahari',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '9',
                'enunciado' => 'Qual é o nome do maior rio do Brasil?',
                'alternativa_a' => 'Rio São Francisco',
                'alternativa_b' => 'Rio Tocantins',
                'alternativa_c' => 'Rio Amazonas',
                'alternativa_d' => 'Rio Paraná',
                'resposta_correta' => 'C',
            ],
            // SÉRIE 1
            [
                'serie' => '1',
                'enunciado' => 'Qual é o maior órgão do corpo humano?',
                'alternativa_a' => 'Coração',
                'alternativa_b' => 'Fígado',
                'alternativa_c' => 'Pele',
                'alternativa_d' => 'Pulmão',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '1',
                'enunciado' => 'Qual é o símbolo químico do ouro?',
                'alternativa_a' => 'Au',
                'alternativa_b' => 'Ag',
                'alternativa_c' => 'Fe',
                'alternativa_d' => 'O',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '1',
                'enunciado' => 'Qual é a velocidade da luz no vácuo?',
                'alternativa_a' => '300.000 km/s',
                'alternativa_b' => '150.000 km/s',
                'alternativa_c' => '1.080 km/h',
                'alternativa_d' => '3.000 km/s',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '1',
                'enunciado' => 'Qual é o maior planeta do Sistema Solar?',
                'alternativa_a' => 'Terra',
                'alternativa_b' => 'Júpiter',
                'alternativa_c' => 'Saturno',
                'alternativa_d' => 'Marte',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '1',
                'enunciado' => 'Qual é o maior animal terrestre?',
                'alternativa_a' => 'Elefante',
                'alternativa_b' => 'Girafa',
                'alternativa_c' => 'Rinoceronte',
                'alternativa_d' => 'Hipopótamo',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '1',
                'enunciado' => 'Qual é o maior oceano do mundo?',
                'alternativa_a' => 'Atlântico',
                'alternativa_b' => 'Índico',
                'alternativa_c' => 'Pacífico',
                'alternativa_d' => 'Ártico',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '1',
                'enunciado' => 'Qual é o nome do processo de transformação da lagarta em borboleta?',
                'alternativa_a' => 'Metamorfose',
                'alternativa_b' => 'Fotossíntese',
                'alternativa_c' => 'Respiração',
                'alternativa_d' => 'Digestão',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '1',
                'enunciado' => 'Qual é o nome do satélite natural da Terra?',
                'alternativa_a' => 'Lua',
                'alternativa_b' => 'Sol',
                'alternativa_c' => 'Marte',
                'alternativa_d' => 'Vênus',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '1',
                'enunciado' => 'Qual é o nome do maior rio do mundo?',
                'alternativa_a' => 'Nilo',
                'alternativa_b' => 'Amazonas',
                'alternativa_c' => 'Yangtzé',
                'alternativa_d' => 'Mississipi',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '1',
                'enunciado' => 'Qual é o nome do maior deserto do mundo?',
                'alternativa_a' => 'Saara',
                'alternativa_b' => 'Atacama',
                'alternativa_c' => 'Gobi',
                'alternativa_d' => 'Kalahari',
                'resposta_correta' => 'A',
            ],
            // SÉRIE 2
            [
                'serie' => '2',
                'enunciado' => 'Qual é o símbolo químico do ouro?',
                'alternativa_a' => 'Au',
                'alternativa_b' => 'Ag',
                'alternativa_c' => 'Fe',
                'alternativa_d' => 'O',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '2',
                'enunciado' => 'Qual é a velocidade da luz no vácuo?',
                'alternativa_a' => '300.000 km/s',
                'alternativa_b' => '150.000 km/s',
                'alternativa_c' => '1.080 km/h',
                'alternativa_d' => '3.000 km/s',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '2',
                'enunciado' => 'Qual é o maior planeta do Sistema Solar?',
                'alternativa_a' => 'Terra',
                'alternativa_b' => 'Júpiter',
                'alternativa_c' => 'Saturno',
                'alternativa_d' => 'Marte',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '2',
                'enunciado' => 'Qual é o maior animal terrestre?',
                'alternativa_a' => 'Elefante',
                'alternativa_b' => 'Girafa',
                'alternativa_c' => 'Rinoceronte',
                'alternativa_d' => 'Hipopótamo',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '2',
                'enunciado' => 'Qual é o maior oceano do mundo?',
                'alternativa_a' => 'Atlântico',
                'alternativa_b' => 'Índico',
                'alternativa_c' => 'Pacífico',
                'alternativa_d' => 'Ártico',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '2',
                'enunciado' => 'Qual é o nome do processo de transformação da lagarta em borboleta?',
                'alternativa_a' => 'Metamorfose',
                'alternativa_b' => 'Fotossíntese',
                'alternativa_c' => 'Respiração',
                'alternativa_d' => 'Digestão',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '2',
                'enunciado' => 'Qual é o nome do satélite natural da Terra?',
                'alternativa_a' => 'Lua',
                'alternativa_b' => 'Sol',
                'alternativa_c' => 'Marte',
                'alternativa_d' => 'Vênus',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '2',
                'enunciado' => 'Qual é o nome do maior rio do mundo?',
                'alternativa_a' => 'Nilo',
                'alternativa_b' => 'Amazonas',
                'alternativa_c' => 'Yangtzé',
                'alternativa_d' => 'Mississipi',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '2',
                'enunciado' => 'Qual é o nome do maior deserto do mundo?',
                'alternativa_a' => 'Saara',
                'alternativa_b' => 'Atacama',
                'alternativa_c' => 'Gobi',
                'alternativa_d' => 'Kalahari',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '2',
                'enunciado' => 'Qual é o maior órgão do corpo humano?',
                'alternativa_a' => 'Coração',
                'alternativa_b' => 'Fígado',
                'alternativa_c' => 'Pele',
                'alternativa_d' => 'Pulmão',
                'resposta_correta' => 'C',
            ],
            // SÉRIE 3
            [
                'serie' => '3',
                'enunciado' => 'Qual é a velocidade da luz no vácuo?',
                'alternativa_a' => '300.000 km/s',
                'alternativa_b' => '150.000 km/s',
                'alternativa_c' => '1.080 km/h',
                'alternativa_d' => '3.000 km/s',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '3',
                'enunciado' => 'Qual é o maior planeta do Sistema Solar?',
                'alternativa_a' => 'Terra',
                'alternativa_b' => 'Júpiter',
                'alternativa_c' => 'Saturno',
                'alternativa_d' => 'Marte',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '3',
                'enunciado' => 'Qual é o maior animal terrestre?',
                'alternativa_a' => 'Elefante',
                'alternativa_b' => 'Girafa',
                'alternativa_c' => 'Rinoceronte',
                'alternativa_d' => 'Hipopótamo',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '3',
                'enunciado' => 'Qual é o maior oceano do mundo?',
                'alternativa_a' => 'Atlântico',
                'alternativa_b' => 'Índico',
                'alternativa_c' => 'Pacífico',
                'alternativa_d' => 'Ártico',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '3',
                'enunciado' => 'Qual é o nome do processo de transformação da lagarta em borboleta?',
                'alternativa_a' => 'Metamorfose',
                'alternativa_b' => 'Fotossíntese',
                'alternativa_c' => 'Respiração',
                'alternativa_d' => 'Digestão',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '3',
                'enunciado' => 'Qual é o nome do satélite natural da Terra?',
                'alternativa_a' => 'Lua',
                'alternativa_b' => 'Sol',
                'alternativa_c' => 'Marte',
                'alternativa_d' => 'Vênus',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '3',
                'enunciado' => 'Qual é o nome do maior rio do mundo?',
                'alternativa_a' => 'Nilo',
                'alternativa_b' => 'Amazonas',
                'alternativa_c' => 'Yangtzé',
                'alternativa_d' => 'Mississipi',
                'resposta_correta' => 'B',
            ],
            [
                'serie' => '3',
                'enunciado' => 'Qual é o nome do maior deserto do mundo?',
                'alternativa_a' => 'Saara',
                'alternativa_b' => 'Atacama',
                'alternativa_c' => 'Gobi',
                'alternativa_d' => 'Kalahari',
                'resposta_correta' => 'A',
            ],
            [
                'serie' => '3',
                'enunciado' => 'Qual é o maior órgão do corpo humano?',
                'alternativa_a' => 'Coração',
                'alternativa_b' => 'Fígado',
                'alternativa_c' => 'Pele',
                'alternativa_d' => 'Pulmão',
                'resposta_correta' => 'C',
            ],
            [
                'serie' => '3',
                'enunciado' => 'Qual é o símbolo químico do ouro?',
                'alternativa_a' => 'Au',
                'alternativa_b' => 'Ag',
                'alternativa_c' => 'Fe',
                'alternativa_d' => 'O',
                'resposta_correta' => 'A',
            ],
        ];
        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}
